name: opensubtitles_api
version: 0.1.0
author: Ariel Barabas <ariel.baras@gmail.com>
description: OpenSubtitles.org library for Dart
homepage: https://github.com/abarabas/dart-xmlrpc
environment:
  sdk: '>=1.3.0'
dependencies:
  fixnum: '>=0.9.0 <1.0.0'
  http: '>=0.11.1 <1.0.0'
  xmlrpc:
    git: git://github.com/abarabas/dart-xmlrpc.git
    version: '>=2.0.0 <3.0.0'
